#!/bin/sh
# Copyright (C) 2011  INRIA and Microsoft Corporation


BASEDIR="`pwd`"
TOOLDIR="$BASEDIR/TOOLS"

. $TOOLDIR/env_setup

ARGS="-I $LIBRARY_DIR"
if [ "$1" = "smt_tests" ]; then
  ARGS="$ARGS --method smt"
fi

export TLAPM="$TLAPM_BIN $ARGS"
export STRETCH=${STRETCH:-5}
export LOGFILE="$BASEDIR/tests.log"
export PATH=$BASEDIR/lib/tlaps/bin/:$PATH

echo "###### `date '+%Y-%m-%d %H:%M:%S'` $0 $@" >>"$LOGFILE"

find "$1" -name '*.tlaps' -prune -o -name '*_test.tla' -print | sort | (

  total=0
  success=0
  fail=0

  while read f; do
    total=`expr $total + 1`
    printf "  %s " "$f"
    export FILE="`basename $f`"
    export DIR="`dirname $f`"
    echo "    $f" >>"$LOGFILE"
    echo | (cd $DIR; /usr/bin/time "$TOOLDIR"/time_one_test "$FILE" "$TOOLDIR" \
                     2>>"$LOGFILE")
    case $? in
      0) echo ok
         success=`expr $success + 1`
         #rm -f "$f.out" "$f.err"
         ;;
      *) echo FAILED
         fail=`expr $fail + 1`
         ;;
    esac
    rm -rf ${f}ps
  done

  echo
  echo "total:   $total"
  echo "success: $success"
  echo "failure: $fail"

  case $fail in
    0) exit 0;;
    *) echo
       echo "**** WARNING: SOME TESTS FAILED ****"
       echo
       exit 3;;
  esac
)
